from . import res_company
from . import res_config
from . import account_move
from . import account_journal
from . import account_move_line
from . import account_vninvoice_type
from . import account_vninvoice_serial
from . import account_vninvoice_template
from . import account_journal_dashboard
from . import ir_actions_report