import base64
from odoo import models


class IrActionsReport(models.Model):
    _inherit = 'ir.actions.report'

    def _post_pdf(self, save_in_attachment, pdf_content=None, res_ids=None):
        # OVERRIDE: replace the PDF version generated by Odoo's standard invoice report with the converted version of VN-invoice
        if self.model == 'account.move' and res_ids and len(res_ids) == 1:
            invoice = self.env['account.move'].browse(res_ids)
            if not invoice.journal_id.send_mail_einvoice_disabled and invoice.type in invoice.get_sale_types() and invoice.einvoice_state != 'not_issued':
                if invoice.vninvoice_transactionid:
                    if invoice.journal_id.einvoice_send_mail_option == 'converted' and invoice.check_vninvoice_approved_and_signed:
                        invoice._ensure_vninvoice_converted_file()
                        pdf_content = base64.b64decode(invoice.vninvoice_converted_file)
                    else:
                        invoice._ensure_vninvoice_representation_files()
                        pdf_content = base64.b64decode(invoice.vninvoice_representation_pdf)
        return super(IrActionsReport, self)._post_pdf(save_in_attachment, pdf_content, res_ids)