from . import administrative_region
from . import admin_region_payroll_contrib
from . import hr_contract
from . import hr_employee
from . import hr_payroll_contribution_history
from . import hr_payroll_contribution_register
from . import hr_payroll_contribution_type
from . import hr_payslip_contribution_line
from . import res_company
