from . import hr_payroll_payslips_by_employees
from . import hr_payroll_contribution_register_report
from . import abstract_hr_payroll_contrib_action
from . import hr_payroll_contrib_action_change_base
from . import hr_payroll_contrib_action_change_rates
from . import hr_payroll_contrib_action_done
from . import hr_payroll_contrib_action_resume
from . import hr_payroll_contrib_action_suspend
from . import hr_payroll_contrib_action_edit_date_end
from . import hr_payroll_contrib_action_edit_date_start
from . import update_contract_advantage
