from . import mobile_device_token
from . import mobile_notification
from . import mobile_notifications_detail
from . import mail_thread
from . import res_partner
from . import res_config_setting
from . import mail_channel
from . import mail_channel_partner
from . import mail_message
