from odoo import models, fields


class MobileDeviceToken(models.Model):
    _name = 'mobile.device.token'
    _description = "Mobile Device Token"

    token = fields.Char(string='Token', readonly=True,
                        help="Code snippets generated by notification service providers")
    partner_id = fields.Many2one('res.partner', string='Partner', readonly=True, ondelete='cascade')
    consecutive_error = fields.Integer(string='Number of consecutive error', readonly=True, default=0,
                                       help="If a token has 50 consecutive error submissions, it will be unlink")
    platform = fields.Char(string='Platform', readonly=True, help="The operating system used by the mobile device")
    package_name = fields.Char(string='Package name', readonly=True,
                               help="The name of the project that is registered with google play, apple store or other service provider")
