from . import abstract_custom_declaration_tax_group
from . import account_journal
from . import account_chart_template
from . import product_template
from . import stock_location
from . import stock_move
from . import stock_picking
from . import stock_picking_type
from . import stock_warehouse
from . import res_partner
from . import purchase_order
from . import sale_order
from . import custom_declaration_line
from . import abstract_custom_declaration_tax
from . import custom_declaration_tax_import
from . import custom_declaration_tax_import_group
from . import custom_declaration_tax_export
from . import custom_declaration_tax_export_group
from . import abstract_custom_declaration
from . import custom_declaration_import
from . import custom_declaration_export
from . import account_move
from . import res_company
from . import res_config_settings
from . import stock_landed_cost
from . import account_tax
from . import product_product
from . import custom_declaration_line_extra_expense
