from . import ir_module_module
from . import account_move
from . import account_asset
from . import account_asset_category
from . import account_asset_depreciation_line
from . import account_asset_revaluation_line
from . import account_move_line
from . import product
from . import res_company
from . import account_chart_template
