from . import account_asset_asset
from . import account_asset_depreciation_line
from . import account_asset_revaluation_line
from . import account_asset_category
from . import stock_move_line
from . import stock_move
from . import stock_location
from . import stock_picking_type
from . import stock_picking
from . import account_move
from . import stock_warehouse
from . import product_product
from . import stock_landed_cost
from . import stock_production_lot
from . import account_move_line
