from . import account_chart_template
from . import voucher_type
from . import product_template
from . import product_product
from . import account_journal
from . import voucher_voucher
from . import voucher_issue_order
from . import voucher_move_order
from . import voucher_give_order
from . import stock_production_lot
from . import stock_move
from . import stock_picking_type
from . import res_company
from . import res_config
from . import account_move
from . import account_move_line
from . import stock_warehouse
from . import stock_move_line
