from odoo import fields, models, api, _


class StockMoveLine(models.Model):
    _inherit = 'stock.move.line'

    voucher_id = fields.Many2one('voucher.voucher', string='Promotion Voucher', related='lot_id.voucher_id', readonly=True, store=True,
                                   help="The voucher that was generated by this stock move line.")

    def _prepare_voucher_data(self, lot_id):
        return{
            'lot_id': lot_id.id,
            'issue_order_id': self.move_id.order_id.id,
            'issue_date': fields.Date.today(),
            }

    def create_promotion_voucher(self, lot_id):
        return self.env['voucher.voucher'].create(self._prepare_voucher_data(lot_id))

