from . import ir_module_module
from . import resource_calendar
from . import hr_salary_cycle
from . import res_company
from . import res_config_settings
from . import browsable_object
from . import hr_contribution_category
from . import abstract_hr_advantage
from . import hr_advantage_template
from . import hr_job_advantage
from . import hr_contract_advantage
from . import hr_job
from . import hr_contract
from . import hr_employee
from . import hr_payroll_structure
from . import hr_contribution_register
from . import hr_salary_rule_category
from . import abstract_hr_salary_rule
from . import hr_salary_rule
from . import hr_rule_input
from . import payslip_leave_interval
from . import resource_calendar_leaves
from . import hr_working_month_calendar_line
from . import hr_working_month_calendar
from . import hr_payslip
from . import hr_payslip_line
from . import hr_payslip_worked_days
from . import hr_payslip_input
from . import hr_payslip_run
from . import hr_leave_type
from . import hr_leave
from . import hr_payroll_contribution_type
from . import hr_payroll_contribution_register
from . import hr_payroll_contribution_history
from . import hr_payslip_contribution_line
from . import payslip_personal_income_tax
from . import personal_tax_rule_escalation
from . import personal_tax_rule
from . import res_country
from . import hr_employee_relative
