from . import res_company
from . import res_config_settings
from . import document_tag_category
from . import document_tag
from . import document_action
from . import document_action_set_tag
from . import document_workspace
from . import document_document
from . import document_share
from . import ir_attachment
from . import document_team
from . import document_auto_generate_rule
