from . import fleet_vehicle_trip
from . import route_waypoint
from . import route_route
from . import trip_section
from . import fleet_vehicle_trip_waypoint
from . import hr_employee
from . import route_section
from . import res_partner
from . import fleet_vehicle_log_services
from . import fleet_vehicle_odometer
from . import fleet_vehicle
