from . import account_analytic_account
from . import abstract_vehicle_service_revenue
from . import account_move_line
from . import account_analytic_line
from . import account_analytic_group
from . import fleet_service_type
from . import fleet_vehicle_log_services
from . import account_move
from . import fleet_vehicle_model_brand
from . import fleet_vehicle_model
from . import fleet_vehicle
