from . import account_analytic_account
from . import abstract_vehicle_cost_revenue
from . import account_move_line
from . import account_analytic_line
from . import account_analytic_group
from . import fleet_service_type
from . import fleet_vehicle_cost
from . import abstract_fleet_vehicle_log
from . import fleet_vehicle_log_fuel
from . import fleet_vehicle_log_services
from . import fleet_vehicle_log_contract
from . import account_move
from . import fleet_vehicle_model_brand
from . import fleet_vehicle_model
from . import fleet_vehicle
