import base64

from odoo import models


class IrActionsReport(models.Model):
    _inherit = 'ir.actions.report'

    def _post_pdf(self, save_in_attachment, pdf_content=None, res_ids=None):
        # OVERRIDE: replace the PDF version generated by Odoo's standard invoice report with the converted version of E-Invoice
        if self.model == 'account.move' and res_ids and len(res_ids) == 1:
            invoice = self.env['account.move'].browse(res_ids)
            if not invoice.journal_id.send_mail_einvoice_disabled and invoice.move_type == 'out_invoice' and invoice.einvoice_state != 'not_issued':
                if invoice.journal_id.einvoice_send_mail_option == 'converted':
                    invoice._ensure_einvoice_converted_file()
                    pdf_content = base64.b64decode(invoice.einvoice_converted_file)
                else:
                    invoice._ensure_einvoice_representation_files()
                    pdf_content = base64.b64decode(invoice.einvoice_representation_pdf)
        return super(IrActionsReport, self)._post_pdf(save_in_attachment, pdf_content, res_ids)
