from . import stock_move_line
from . import stock_production_lot
from . import product_category
from . import maintenance_equipment
from . import product_template
from . import product_product
from . import stock_picking_type
from . import maintenance_request
from . import stock_move