{
    'name': "Stock Report Common",
    'name_vi_VN': "Báo cáo kho thông dụng",

    'summary': """
Common utilities for stock reporting""",
    'summary_vi_VN': """
Các tiện tích thông dụng cho báo cáo kho""",

    'description': """
What it does
============
This is a technical module that aims to provide utilities and tools for stock reporting generated by other stock report modules

Editions Supported
==================
1. Community Edition
2. Enterprise Edition
    """,
    'description_vi_VN': """
Module này làm gì
=================
* Đây là module kỹ thuật nhằm cung cấp các tiện ích và công cụ cho các báo cáo kho được tạo bởi các module báo cáo kho khác.

Ấn bản hỗ trợ
=============
1. Ấn bản cộng đồng
2. Ấn bản doanh nghiệp
    """,

    'author' : 'T.V.T Marine Automation (aka TVTMA),Viindoo',
    'website': 'https://viindoo.com',
    'live_test_url': "https://v14demo-int.viindoo.com",
    'live_test_url_vi_VN': "https://v14demo-vn.viindoo.com",
    'support': 'apps.support@viindoo.com',

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/module/module_data.xml
    # for the full list
    'category': 'Hidden',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['to_location_warehouse', 'stock_account', 'to_base'],

    # always loaded
    'data': [
        'wizard/wizard_stock_report_common_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'price': 99.9,
    'currency': 'EUR',
    'license': 'OPL-1',
}
