{
    'name': "Inter-Company Storable Products Purchase and Sales",
    'name_vi_VN': "Giao dịch liên công ty - lưu trữ sản phẩm mua và bán",
    'summary': """Integrate inter-company sales & purchase process with Inventory""",
    'summary_vi_VN': """Tích hợp quy trình mua và bán hàng liên công ty với hàng tồn kho""",

    'description': """
What it does
============
* Conducing inter company transactions between 2 companies A and B in the same system:
    * when validating a SO in company A, a PO with operation type will be auto created in company B 
    * When validating a PO in company A, a SO with warehouse infomation will be auto created in company B  
    * Auto validate SO/PO (which were auto generated by system)
    
Editions Supported
==================
1. Community Edition
2. Enterprise Edition

    """,

    'description_vi_VN': """
Ứng dụng này làm gì
===================
* Khi thực hiện giao dịch mua bán liên công ty giữa 2 công ty A và B trong hệ thống:
    * Khi xác nhận đơn hàng bán ở công ty A, tự động tạo đơn hàng mua với kiểu vận chuyển ở công ty B
    * Khi xác nhận đơn hàng mua ở công ty A, tự động tạo đơn hàng bán với thông tin kho  ở công ty B
    * Tự động xác nhận đơn hàng (được sinh tự động) nếu được thiết lập
    
Ấn bản được Hỗ trợ
==================
1. Ấn bản Community
2. Ấn bản Enterprise

    """,

    'author': "T.V.T Marine Automation (aka TVTMA),Viindoo",
    'website': "https://viindoo.com",
    'live_test_url': "https://v13demo-int.erponline.vn",
    'live_test_url_vi_VN': "https://v13demo-vn.erponline.vn",
    'support': "apps.support@viindoo.com",
    'category': 'Productivity',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['to_inter_company_sale_purchase', 'purchase_stock', 'sale_stock'],

    # always loaded
    'data': [
        'views/res_config_settings_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'price': 99.9,
    'currency': 'EUR',
    'license': 'OPL-1',
}
