from odoo import models, fields

class FleetVehicleLogServices(models.Model):
    _inherit = 'fleet.vehicle.log.services'

    created_from_stock_move_id = fields.Many2one('stock.move', string='Stock Move', readonly=True,
                                                 groups='stock.group_stock_user',
                                                 ondelete='restrict',
                                                 help="This field is to indicated that the service was generated by a stock move.")
    created_from_stock_stock_picking_id = fields.Many2one('stock.picking', related='created_from_stock_move_id.picking_id', string='Stock Reference',
                                                          groups='stock.group_stock_user',
                                                          readonly=True, store=True, ondelete='restrict',
                                                          help="The source stock picking document that generated this vehicle service.")
