from . import sale_subscription_close_reason
from . import sale_subscription_line
from . import sale_subscription
from . import sale_subscription_template
from . import payment_token
from . import product_template
from . import res_partner
from . import sale_order_line
from . import sale_order
from . import account_analytic_account
from . import account_move_line
from . import sale_subscription_stage
from . import sale_subscription_snapshot
from . import sale_subscription_automation
from . import res_config_settings
from . import digest_digest
