from . import ir_module_module
from . import helpdesk_ticket_type
from . import res_company
from . import helpdesk_ticket
from . import helpdesk_team
from . import helpdesk_stage
from . import helpdesk_tag
from . import res_partner
from . import res_users
from . import res_config_settings
from . import digest_digest
from . import helpdesk_sla
from . import helpdesk_sla_line
