from . import ir_module_category
from . import odoo_module_version_download_stat
from . import res_company
from . import res_config_settings
from . import software_author
from . import odoo_module_version_image
from . import odoo_module_version
from . import odoo_module
from . import product_template
from . import product_product
from . import odoo_version
from . import product_license
from . import product_license_version
from . import git_branch
from . import git_repository
from . import account_move_line
from . import account_move
from . import res_partner
