from . import hr_contract
from . import hr_employee_base
from . import hr_overtime_plan_line
from . import hr_overtime_plan
from . import hr_overtime_reason
from . import hr_overtime_rule_code
from . import hr_overtime_rule
from . import abstract_overtime_plan_line_match
from . import res_company
from . import resource_calendar
from . import res_config_settings
