from . import product_template
from . import account_move
from . import account_move_line
from . import account_partial_reconcile
from . import account_full_reconcile
from . import account_payment
from . import payment_acquirer
from . import payment_transaction
from . import res_partner
from . import wallet
